In [1]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Importing the Dataset
dataset = pd.read_csv('../Large_data/mla2z/Data.csv')

In [3]:
#matrix the feature
X = dataset.iloc[:,:-1].values

In [4]:
#Creating th dependent 
y = dataset.iloc[:,3].values

In [5]:
#Handling the missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [6]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [7]:
#encoding Categorical data - new way 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(), [0])], remainder= 'passthrough')
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [8]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [9]:
#Dummy Encoding - old way
label_Encoder = LabelEncoder()
y = label_Encoder.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [10]:
#Splitting the dataset into train test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y,test_size = 0.25, random_state = 0)

In [11]:
#Feature Scaling - Noralization
print(X_train)
print(X_test)

[[1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]]


In [12]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_train[:,3:] = scalar.fit_transform(X_train[:,3:])
X_test[:,3:]  = scalar.fit_transform(X_test[:,3:])
print(X_train)

[[1.0 0.0 0.0 -0.2029809015697542 0.44897082661305115]
 [0.0 0.0 1.0 -1.821689357126023 -1.4170641714974423]
 [0.0 0.0 1.0 0.08478949052913817 -1.0242146982110225]
 [1.0 0.0 0.0 1.5775983995421416 1.62751924647231]
 [0.0 0.0 1.0 -0.041110056014127316 -0.14030338331657835]
 [1.0 0.0 0.0 0.930115017319634 0.9400326682210757]
 [1.0 0.0 0.0 -0.526722592681008 -0.4349404882813931]]
