In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('../../Large_data/Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
X = X[:,1:]

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
#Doing categorical encodeing for color column
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(), [0])], remainder= 'passthrough')
X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
X_train

array([[ 0.98019606, -0.98019606,  0.58164944, -0.88670699],
       [-1.02020406,  1.02020406, -0.60673761,  1.46173768],
       [ 0.98019606, -0.98019606, -0.01254409, -0.5677824 ],
       ...,
       [-1.02020406,  1.02020406, -0.21060859, -0.50979612],
       [ 0.98019606, -0.98019606, -1.10189888, -0.45180983],
       [ 0.98019606, -0.98019606, -1.20093113,  1.40375139]])

In [8]:
#implementiong KNN
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [9]:
print(classifier.predict(sc.transform(ct.transform([['Male',30,87000]]))))

[0]


In [10]:
y_pred = classifier.predict(X_test)


In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[64  4]
 [ 3 29]]


0.93

In [12]:
#implementing SVM
from sklearn.svm import SVC
classifier = SVC(kernel='linear', random_state=0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [13]:
print(classifier.predict(sc.transform(ct.transform([['Male',30,87000]]))))

[0]


In [14]:
y_pred = classifier.predict(X_test)


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[66  2]
 [ 9 23]]


0.89