In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('train.csv')

In [3]:
data.head()

pet_id           issue_date         listing_date  condition  \
0  ANSL_69903  2016-07-10 00:00:00  2016-09-21 16:25:00        2.0   
1  ANSL_69902  2016-07-10 00:00:00  2016-09-21 16:25:00        2.0   
2  ANSL_66892  2013-11-21 00:00:00  2018-12-27 17:47:00        1.0   
3  ANSL_69750  2014-09-28 00:00:00  2016-10-19 08:24:00        NaN   
4  ANSL_71623  2016-12-31 00:00:00  2019-01-25 18:30:00        1.0   

    color_type  length(m)  height(cm)  X1  X2  breed_category  pet_category  
0  Brown Tabby       0.80        7.78  13   9             0.0             1  
1         Pink       0.80        7.78  13   9             0.0             1  
2        White       0.72       14.19  13   9             0.0             2  
3        Brown       0.15       40.90  15   4             2.0             4  
4        White       0.62       17.82   0   1             0.0             2

In [4]:
data.isnull().mean()

pet_id            0.000000
issue_date        0.000000
listing_date      0.000000
condition         0.078418
color_type        0.000000
length(m)         0.000000
height(cm)        0.000000
X1                0.000000
X2                0.000000
breed_category    0.000000
pet_category      0.000000
dtype: float64

In [5]:
data_X = data.drop(labels=["pet_id","issue_date","listing_date","breed_category","pet_category"],axis=1)
data_y = data[["breed_category","pet_category"]]

In [6]:
data_X.isnull().mean()

condition     0.078418
color_type    0.000000
length(m)     0.000000
height(cm)    0.000000
X1            0.000000
X2            0.000000
dtype: float64

In [7]:
data_X.fillna(np.float(3.0),inplace=True)

In [8]:
data_X.condition.unique()

array([2., 1., 3., 0.])

In [9]:
data_X.isnull().mean()

condition     0.0
color_type    0.0
length(m)     0.0
height(cm)    0.0
X1            0.0
X2            0.0
dtype: float64

In [10]:
data_X.head()

condition   color_type  length(m)  height(cm)  X1  X2
0        2.0  Brown Tabby       0.80        7.78  13   9
1        2.0         Pink       0.80        7.78  13   9
2        1.0        White       0.72       14.19  13   9
3        3.0        Brown       0.15       40.90  15   4
4        1.0        White       0.62       17.82   0   1

In [11]:
test = pd.read_csv("test.csv")

In [12]:
test.head()

pet_id           issue_date         listing_date  condition  \
0  ANSL_75005  2005-08-17 00:00:00  2017-09-07 15:35:00        0.0   
1  ANSL_76663  2018-11-15 00:00:00  2019-05-08 17:24:00        1.0   
2  ANSL_58259  2012-10-11 00:00:00  2018-04-02 16:51:00        1.0   
3  ANSL_67171  2015-02-13 00:00:00  2018-04-06 07:25:00        1.0   
4  ANSL_72871  2017-01-18 00:00:00  2018-04-26 13:42:00        1.0   

     color_type  length(m)  height(cm)  X1  X2  
0         Black       0.87       42.73   0   7  
1  Orange Tabby       0.06        6.71   0   1  
2         Black       0.24       41.21   0   7  
3         Black       0.29        8.46   7   1  
4         Brown       0.71       30.92   0   7

In [13]:
test1 = test.drop(labels=["pet_id","issue_date","listing_date"], axis=1)

In [14]:
test1.head()

condition    color_type  length(m)  height(cm)  X1  X2
0        0.0         Black       0.87       42.73   0   7
1        1.0  Orange Tabby       0.06        6.71   0   1
2        1.0         Black       0.24       41.21   0   7
3        1.0         Black       0.29        8.46   7   1
4        1.0         Brown       0.71       30.92   0   7

In [15]:
test1.isnull().mean()

condition     0.076685
color_type    0.000000
length(m)     0.000000
height(cm)    0.000000
X1            0.000000
X2            0.000000
dtype: float64

In [16]:
test1.fillna(np.float(3.0),inplace=True)

In [17]:
test1.isnull().mean()

condition     0.0
color_type    0.0
length(m)     0.0
height(cm)    0.0
X1            0.0
X2            0.0
dtype: float64

In [18]:
 from sklearn.compose import ColumnTransformer
 from sklearn.preprocessing import OneHotEncoder
 ct2 = ColumnTransformer(transformers = [('encoder',OneHotEncoder(sparse=False), [1])], remainder= 'passthrough',verbose=1)
 ct2.fit(data_X)

[ColumnTransformer] ....... (1 of 2) Processing encoder, total=   0.0s
[ColumnTransformer] ..... (2 of 2) Processing remainder, total=   0.0s


ColumnTransformer(n_jobs=None, remainder='passthrough', sparse_threshold=0.3,
                  transformer_weights=None,
                  transformers=[('encoder',
                                 OneHotEncoder(categories='auto', drop=None,
                                               dtype=<class 'numpy.float64'>,
                                               handle_unknown='error',
                                               sparse=False),
                                 [1])],
                  verbose=1)

In [19]:
 from sklearn.ensemble import GradientBoostingClassifier

In [61]:
classifier3 =  GradientBoostingClassifier(n_estimators=180,verbose=2,learning_rate=0.5)
classifier3.fit(ct2.transform(data_X),data_y.breed_category)

      Iter       Train Loss   Remaining Time 
         1        6930.2286           24.04s
         2        4840.5647           23.61s
         3        3873.9105           26.24s
         4        3416.1957           29.36s
         5        3133.5913           31.45s
         6        3023.1182           33.81s
         7        2906.4885           35.43s
         8        2866.0117           36.13s
         9        2844.7074           39.44s
        10        2829.2058           38.45s
        11        2807.8347           39.86s
        12        2793.7248           39.70s
        13        2783.8286           39.24s
        14        2755.5362           38.59s
        15        2743.2728           38.00s
        16        2736.8219           37.30s
        17        2729.2444           38.01s
        18        2720.2899           37.41s
        19        2713.7218           36.52s
        20        2704.3545           35.73s
        21        2698.3377           35.15s
        2

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.5, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=180,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=2,
                           warm_start=False)

In [62]:
classifier4 =  GradientBoostingClassifier(n_estimators=500,verbose=2,learning_rate=0.090)
classifier4.fit(ct2.transform(data_X),data_y.pet_category)

      Iter       Train Loss   Remaining Time 
         1       14661.3160            3.08m
         2       13787.1512            2.97m
         3       13110.6969            2.99m
         4       12552.4012            2.67m
         5       12091.9943            2.52m
         6       11692.4084            2.48m
         7       11340.1817            2.52m
         8       11023.3155            2.60m
         9       10747.9988            2.63m
        10       10489.0045            2.60m
        11       10262.3961            2.56m
        12       10070.0721            2.48m
        13        9890.9449            2.55m
        14        9713.8214            2.61m
        15        9553.0535            2.67m
        16        9996.5398            2.71m
        17        9263.7924            2.73m
        18        9113.9141            2.79m
        19        9010.6909            2.81m
        20        8876.9558            2.82m
        21        8764.1883            2.84m
        2

       183        5335.6555            1.48m
       184        5332.0503            1.47m
       185        5325.9983            1.46m
       186        5322.0759            1.46m
       187        5315.1132            1.45m
       188        5310.0722            1.45m
       189        5304.7843            1.45m
       190        5300.8199            1.44m
       191        5294.0036            1.44m
       192        5289.0321            1.43m
       193        5286.0987            1.42m
       194        5283.1317            1.42m
       195        5277.4825            1.41m
       196        5273.7286            1.41m
       197        5269.3513            1.41m
       198        5264.1740            1.40m
       199        5259.8014            1.40m
       200        5253.6862            1.39m
       201        5247.9139            1.38m
       202        5244.9432            1.38m
       203        5241.9674            1.38m
       204        5235.8876            1.37m
       205

       366        4732.7787           38.52s
       367        4730.1576           38.25s
       368        4728.0385           37.98s
       369        4726.6462           37.71s
       370        4724.7341           37.44s
       371        4722.5644           37.13s
       372        4721.1005           36.87s
       373        4718.8376           36.64s
       374        4716.7259           36.38s
       375        4714.1681           36.10s
       376        4712.8962           35.88s
       377        4710.1729           35.64s
       378        4708.4858           35.36s
       379        4705.1910           35.07s
       380        4702.6352           34.80s
       381        4701.1525           34.56s
       382        4698.7447           34.26s
       383        4696.8490           33.99s
       384        4695.2887           33.72s
       385        4691.5454           33.46s
       386        4689.3280           33.20s
       387        4688.4094           32.91s
       388

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.09, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=2,
                           warm_start=False)

In [63]:
data_y.columns

Index(['breed_category', 'pet_category'], dtype='object')

In [64]:
data_y.breed_category

0        0.0
1        0.0
2        0.0
3        2.0
4        0.0
        ... 
18830    0.0
18831    2.0
18832    1.0
18833    1.0
18834    1.0
Name: breed_category, Length: 18835, dtype: float64

In [65]:
Test_breed = classifier3.predict(ct2.transform(test1))
Test_cat = classifier4.predict(ct2.transform(test1))

In [66]:
Train_breed = classifier3.predict(ct2.transform(data_X))
Train_cat = classifier4.predict(ct2.transform(data_X))

In [67]:
from sklearn.metrics import accuracy_score, confusion_matrix
met1 = confusion_matrix(data_y.breed_category,Train_breed)
met2 = confusion_matrix(data_y.pet_category,Train_cat)

In [68]:
met1

array([[8672,  329,    0],
       [ 533, 7824,    0],
       [   0,    0, 1477]])

In [69]:
met2

array([[   81,     2,     3,     2],
       [    0,  5797,  1379,     9],
       [    0,   440, 10169,    12],
       [    0,    35,   108,   798]])

In [70]:
acc = accuracy_score(data_y.breed_category,Train_breed)
acc1 = accuracy_score(data_y.pet_category,Train_cat)

In [71]:
acc

0.9542341385718078

In [72]:
acc1

0.8943456331298115

In [73]:
f = open('result.csv',"w")
count=0
f.write('pet_id,breed_category,pet_category')
for i in range(len(test)):
    f.write(f'\n{test["pet_id"][i]},{int(Test_breed[i])},{int(Test_cat[i])} ')
    count+=1
f.close()

In [74]:
data_X.condition.unique()

array([2., 1., 3., 0.])

In [75]:
test1.condition.unique()

array([0., 1., 2., 3.])