In [1]:
from sklearn.datasets import make_regression

In [3]:
X,y =make_regression(n_samples=1500,n_informative=5,n_features=10,n_targets=2)

In [4]:
X

array([[-1.15141682, -1.34663902, -0.88199939, ..., -0.2714832 ,
         0.28715813,  1.89799946],
       [-0.34819515, -0.74716721,  0.78226032, ..., -0.73514501,
        -1.15575444,  0.95638813],
       [-0.86330889, -0.67078025,  0.36614067, ..., -1.12159201,
        -1.08006708, -0.72993676],
       ...,
       [ 1.29564315, -0.87392778, -1.07738046, ..., -0.00806301,
         2.30693081,  0.06615338],
       [ 0.53509128,  0.81222227, -1.48945685, ..., -1.45801298,
        -0.32667308, -0.04152249],
       [ 0.31894397,  0.505803  ,  0.12263923, ...,  0.22949227,
        -2.43994492, -0.57871734]])

In [5]:
y

array([[ -55.0023879 ,  -32.92905428],
       [ -51.56188994,  -37.25358736],
       [-219.93991967, -181.71745011],
       ...,
       [   2.39259788,    8.37592909],
       [ -81.49617494,  -45.09028903],
       [  16.2943874 ,   13.75515197]])

In [6]:
#Applying Linear Regression
from sklearn.linear_model import LinearRegression
lrregression=LinearRegression()
lrregression.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
test_data=[[-0.35383149,  0.39382202, -2.03033197,  0.08873402, -0.38576581,
        0.0032707 , -0.56476034, -0.67236167,  0.31317233,  1.5208706 ]]

In [8]:
lrregression.predict(test_data)

array([[12.65749912, 33.57786022]])

In [9]:
#Decision Tree regression
from sklearn.tree import DecisionTreeRegressor
dtregressor=DecisionTreeRegressor()
dtregressor.fit(X,y)

/home/vicky/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/vicky/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [11]:
dtregressor.predict(test_data)

array([[16.63678759, 24.36684293]])

In [12]:
#Random Forest regression
from sklearn.ensemble import RandomForestRegressor
rdregressor=RandomForestRegressor()
rdregressor.fit(X,y)

/home/vicky/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [13]:
rdregressor.predict(test_data)


array([[ 8.78868507, 28.2840336 ]])

In [15]:
#Multi output linear regression

from sklearn.svm import LinearSVR
svregressor=LinearSVR()
from sklearn.multioutput import MultiOutputRegressor
mulregressor=MultiOutputRegressor(svregressor)
mulregressor.fit(X,y)

MultiOutputRegressor(estimator=LinearSVR(C=1.0, dual=True, epsilon=0.0,
                                         fit_intercept=True,
                                         intercept_scaling=1.0,
                                         loss='epsilon_insensitive',
                                         max_iter=1000, random_state=None,
                                         tol=0.0001, verbose=0),
                     n_jobs=None)

In [16]:
mulregressor.predict(test_data)

array([[12.65749912, 33.57786022]])